# Generated by Django 5.2 on 2025-05-23 09:05

import django_lifecycle.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('patient_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='患者ID')),
                ('patient_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='患者姓名')),
                ('gender', models.CharField(blank=True, choices=[('M', '男'), ('F', '女'), ('O', '其他'), ('U', '未知')], max_length=1, null=True, verbose_name='性别')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('primary_diagnosis', models.CharField(blank=True, max_length=255, null=True, verbose_name='主要诊断')),
            ],
            options={
                'verbose_name': '患者',
                'verbose_name_plural': '患者',
                'permissions': [('case_patient_view', 'Can view owned resource'), ('case_patient_change', 'Can change owned resource'), ('case_patient_delete', 'Can delete owned resource')],
            },
            bases=(models.Model, django_lifecycle.mixins.LifecycleModelMixin),
        ),
    ]
