# Generated by Django 5.2 on 2025-06-02 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('case', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'permissions': [('case.patient_view', 'Can view owned resource'), ('case.patient_change', 'Can change owned resource'), ('case.patient_delete', 'Can delete owned resource')], 'verbose_name': '患者', 'verbose_name_plural': '患者'},
        ),
        migrations.AlterField(
            model_name='patient',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owned_by', to='auth.group', verbose_name='所有者'),
        ),
    ]
