# Generated by Django 5.2 on 2025-06-02 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0003_alter_patient_options_alter_patient_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'permissions': [('patient_view', 'Can view owned resource'), ('patient_change', 'Can change owned resource'), ('patient_delete', 'Can delete owned resource')], 'verbose_name': '患者', 'verbose_name_plural': '患者'},
        ),
    ]
